// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TallerMecanico.Data;

#nullable disable

namespace TallerMecanico.Migrations
{
    [DbContext(typeof(TallerMecanicoContext))]
    [Migration("20260918065610_FinalizeModel")]
    partial class FinalizeModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TallerMecanico.Models.OrdenServicio", b =>
                {
                    b.Property<int>("PkOrden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkOrden"));

                    b.Property<DateTime>("FechaOrdenSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("IdOrdenServicio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("IdVehiculo")
                        .HasColumnType("int");

                    b.Property<string>("ObservacionOrdenServicio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StatusOrden")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("UsuarioIdOrdenServicio")
                        .HasColumnType("int");

                    b.HasKey("PkOrden");

                    b.HasIndex("IdOrdenServicio")
                        .IsUnique();

                    b.HasIndex("IdVehiculo");

                    b.HasIndex("UsuarioIdOrdenServicio");

                    b.ToTable("OrdenesServicio");
                });

            modelBuilder.Entity("TallerMecanico.Models.Servicio", b =>
                {
                    b.Property<int>("PkServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkServicio"));

                    b.Property<decimal>("CostoServicio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DetalleServicio")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("FechaCancelacionServicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFinServicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicioServicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdServicio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PkOrden")
                        .HasColumnType("int");

                    b.Property<string>("StatusServicio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoServicio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PkServicio");

                    b.HasIndex("IdServicio")
                        .IsUnique();

                    b.HasIndex("PkOrden");

                    b.ToTable("Servicios", null, t =>
                        {
                            t.HasCheckConstraint("CK_Servicio_Costo", "[CostoServicio] >= 0");
                        });
                });

            modelBuilder.Entity("TallerMecanico.Models.Unidad", b =>
                {
                    b.Property<int>("IdVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVehiculo"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("AnioVehiculo")
                        .HasColumnType("int");

                    b.Property<string>("ColorVehiculo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CombustibleVehiculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistroVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("MarcaVehiculo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ModeloVehiculo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PlacasVehiculo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdVehiculo");

                    b.HasIndex("PlacasVehiculo")
                        .IsUnique();

                    b.ToTable("Unidades", null, t =>
                        {
                            t.HasCheckConstraint("CK_Unidad_Anio", "[AnioVehiculo] >= 1900 AND [AnioVehiculo] <= 2100");
                        });
                });

            modelBuilder.Entity("TallerMecanico.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimerApellidoUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PrimerNombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RolUsuario")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TallerMecanico.Models.OrdenServicio", b =>
                {
                    b.HasOne("TallerMecanico.Models.Unidad", "Unidad")
                        .WithMany()
                        .HasForeignKey("IdVehiculo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TallerMecanico.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioIdOrdenServicio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Unidad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TallerMecanico.Models.Servicio", b =>
                {
                    b.HasOne("TallerMecanico.Models.OrdenServicio", "OrdenServicio")
                        .WithMany()
                        .HasForeignKey("PkOrden")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdenServicio");
                });
#pragma warning restore 612, 618
        }
    }
}
